site_name: Mandryl Docs
theme:
  name: shadcn
nav:
  - Home: index.md
  - Notebooks:
    - Porting Datasets to v3.0: port-datasets-to-v3.md
    - Finetuning SmolVLA for the SO-101 Arm: finetune-smolvla-so101.md